@startuml
left to right direction
package "user" {
  (Voir les détails de modules / compétences)
}

:User: --> (Voir les détails de modules / compétences)


newpage
left to right direction
package "admin" {
    (Gérer les modules et compétences dans chaque module)
}

:Admin: --> (Gérer les modules et compétences dans chaque module)

@enduml