@startuml
left to right direction
package "user" {
  (Authentication)
  (Dashboard)
  (Profile)
}

:User: --> (Authentication)
:User: --> (Dashboard)
:User: --> (Profile)


newpage
left to right direction
package "admin" {
    (Authentication)
    (Dashboard)
    (Profile)
}

:Admin: --> (Authentication)
:Admin: --> (Dashboard)
:Admin: --> (Profile)

@enduml