@startuml
left to right direction
package "user" {
  (Compléter les compétences / Module)
  (Parcourir l'avancement d’apprentissage)
  (Parcourir les badges)
}

:User: --> (Compléter les compétences / Module)
:User: --> (Parcourir l'avancement d’apprentissage)
:User: --> (Parcourir les badges)


newpage
left to right direction
package "admin" {
    (Voir le progrès des apprenants)
    (Gérer les badges)
}

:Admin: --> (Voir le progrès des apprenants)
:Admin: --> (Gérer les badges)

@enduml