@startuml
left to right direction
package "student" {
  (Dashboard)
  (Show the total number of modules)
}

:student: --> (Dashboard)
:student: --> (Show the total number of modules)

newpage
left to right direction
package "admin" {
  (Dashboard)
  (Show the total number of modules)
  (Show the total number of users)
}

:admin: --> (Dashboard)
:admin: --> (Show the total number of modules)
:admin: --> (Show the total number of users)

newpage
left to right direction
package "professor" {
  (Dashboard)
  (Show the total number of modules)
  (Show the total number of users)
}

:professor: --> (Dashboard)
:professor: --> (Show the total number of modules)
:professor: --> (Show the total number of users)

@enduml