@startuml
left to right direction
package "student" {
  (Show progress bar for skill completion)
  (Issue a badge for module completion)
}

:student: --> (Show progress bar for skill completion)
:student: --> (Issue a badge for module completion)

newpage
left to right direction
package "admin" {
  (Progress bar for skill completion)
  (Issue a badge for module completion)
}

:admin: --> (Progress bar for skill completion)
:admin: --> (Issue a badge for module completion)
@enduml